version: '3.8'

services:
  db:
    image: docker.io/gaureshgawasmn/techlab-grocery-service-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: qp-assessment
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin

  app:
    image: docker.io/gaureshgawasmn/techlab-grocery-service:0.0.1
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/qp-assessment
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin