server:
  port: 8081
spring:
  profiles:
    active: dev
  security:
    default:
      password: password2
  #  security:
  #    user:
  #      name: admin
  #      password: admin
  #      roles: ADMIN,USER
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate.format_sql: true
  datasource:
    url: jdbc:h2:mem:qp-assessment
#  h2:
#    console:
#      enabled: true
logging:
  file:
    name: logs/app.log
    path: logs
    max-size: 10MB
    max-history: 10
    max-days: 10
  level:
    org:
      springframework: DEBUG