server:
  port: 8082
spring:
  security:
    default:
      password: password
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate.format_sql: true
  datasource:
    #    url: jdbc:h2:mem:qp-assessment
    url: jdbc:mysql://localhost:3306/qp-assessment
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  file:
    name: logs/app.log
    path: logs
    max-size: 10MB
    max-history: 10
    max-days: 10
  level:
    org:
      springframework: DEBUG