server:
  port: 8081
spring:
  profiles:
    active: dev
#  security:
#    user:
#      name: admin
#      password: admin
#      roles: ADMIN,USER
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate.format_sql: true
  datasource:
    url: jdbc:h2:mem:qp-assessment
#  h2:
#    console:
#      enabled: true
logging:
  level:
    org:
      springframework:
        type: trace
      hibernate:
        stat: DEBUG